name: Publish
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  publish:
    uses: sanzenwin/workflows/.github/workflows/pypi-release-publish-private.yml@main
    with:
      os: ubuntu-latest
      plat_name: ""
    permissions:
      contents: write
    secrets: inherit
